type: backtest

# Which period to use for backtesting. Only relevant for type 'backtest'. Please use the format %Y-%m-%d
period:
    start: '2020-01-29'
    end: '2020-09-29'

# Whether to use real or fake money. Only relevant for type 'trade'
# paper_trade: True

# Which strategy to use
strategy: macd

# The exchange to use, see API folder or README for supported exchanges
exchange: binance

# The currency you would like to trade in
symbol: BTCUSDT

# The currencies you would like to trade in. Not used right now
# symbols: 
#     - BNBBTC

# Interval of klines which will be used. Recommended 15m-1h for most strategies, but as low as possible for arbitrage.
interval: 1h

# Amount of money you would like to start with
starting_amount: 50
